// <auto-generated />
using System;
using CitiesManager.Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CitiesManager.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230429075955_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CitiesManager.Core.Domain.Entities.City", b =>
                {
                    b.Property<Guid>("CityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CityID");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityID = new Guid("d14bc922-c581-4181-b23c-5a86a6177c43"),
                            CityName = "New York"
                        },
                        new
                        {
                            CityID = new Guid("8207dd6c-2504-46ba-9dc4-c2361f6f4e1f"),
                            CityName = "London"
                        },
                        new
                        {
                            CityID = new Guid("8d9188e9-b249-4d2b-b564-1fe0e1997bc1"),
                            CityName = "Paris"
                        },
                        new
                        {
                            CityID = new Guid("6bd9f2a9-3f22-47cb-999d-fdd1ab7790aa"),
                            CityName = "Tokyo"
                        },
                        new
                        {
                            CityID = new Guid("9364a092-aad7-48dc-9a71-4a4cf6e02211"),
                            CityName = "Hong Kong"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
